sudo: required
language: node_js
node_js:
  - 15 # use nodejs v10 LTS
cache: 
  directories: 
    - node_modules
branches:
  only:
    - main # build master branch only
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public